# Ime CI workflowa
name: Test Binary Radix Sort

# Ta workflow se zažene ob vsakem pushu na glavno (main) vejo
on:
  push:
    branches: [ main ]

jobs:
  # === Prvi job: Preverjanje testnih datotek ===
  check_tests:
    runs-on: self-hosted  # Uporabimo svoj lokalni runner
    steps:
      # Kloniramo kodo iz repozitorija
      - uses: actions/checkout@v3

      # Preverimo, če obstajajo testne datoteke (npr. input.txt)
      - name: Preveri testne datoteke
        run: |
          if [ ! -f "input.txt" ]; then
            echo "Manjkajo testne datoteke!" > napaka.txt
            exit 1  # Zaključi z napako, če datoteke ni
          else
            echo "Vse testne datoteke so prisotne." > napaka.txt
          fi

      # Shranimo napaka.txt kot artefakt, da ga drugi job lahko prenese
      - name: Naloži napaka.txt kot artefakt
        if: always()  # Vedno naloži artefakt, tudi če test pade
        uses: actions/upload-artifact@v4
        with:
          name: napaka  # Ime artefakta
          path: napaka.txt  # Pot do datoteke

  # === Drugi job: Poženemo teste ===
  run_tests:
    needs: check_tests  # Začne se šele, ko se check_tests zaključi
    runs-on: self-hosted

    # Uporabimo matriko, da teste poženemo za več različnih primerov
    strategy:
      matrix:
        test_case: [1, 2, 3]  # Trije različni testni primeri

    steps:
      # Kloniramo kodo iz repozitorija
      - uses: actions/checkout@v3

      # Prenesemo napaka.txt artefakt iz prvega joba
      - name: Prenesi napaka.txt artefakt
        uses: actions/download-artifact@v3
        with:
          name: napaka

      # Preverimo, če je v napaka.txt zapisano, da testne datoteke manjkajo
      - name: Preveri vsebino napaka.txt
        run: |
          if grep -q "Manjkajo testne datoteke" napaka.txt; then
            echo "Napaka: testne datoteke manjkajo. Testiranje se ne bo izvedlo."
            exit 1  # Zaključi z napako in preskoči nadaljnje korake
          fi

      # Prevedemo program (npr. z uporabo Makefile)
      - name: Prevedi program
        run: make

      # Poženemo testno skripto z argumentom matrike
      - name: Poženi testno skripto
        run: ./run_tests.sh ${{ matrix.test_case }}
