name: Deploy to Docker Hub

on:
  workflow_run:
    workflows: ["Test Binary Radix Sort"]
    branches: [ main ]
    types: [ completed ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t tvoj-dockerhub-username/binary-radix-sort:latest .
      - run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/binary-radix-sort:latest
