# Ime workflowa za testiranje kode
name: Test Binary Radix Sort

# Proženje ob potisku na vejo 'main'
on:
  push:
    branches: [ main ]

jobs:
  # Prvi posel: preveri, ali obstajajo testne skripte
  check_tests:
    runs-on: self-hosted  # Lokalni runner
    steps:
      # Klonira repozitorij
      - uses: actions/checkout@v3

      # Preveri, če obstaja testna skripta
      - run: |
          if [ ! -f "run_tests.sh" ]; then
            echo "Manjkajo testne skripte!" > napaka.txt
            exit 1
          fi
      # Ustvari artefakt z napako (če obstaja)
      - name: Shranjevanje napake
        uses: actions/upload-artifact@v4
        with:
          name: napaka
          path: napaka.txt

  # Drugi posel: pripravi okolje in izvede teste
  run_tests:
    needs: check_tests  # Odvisen od prvega posla
    runs-on: self-hosted
    
    strategy:
      matrix:
        test_case: [1, 2, 3]  # Različni testni primeri

    steps:
      # Prenos artefakta iz prvega posla
      - name: Prenos napake
        uses: actions/download-artifact@v4
        with:
          name: napaka
          path: ./napaka

      # Preveri, če je napaka prisotna
      - run: |
          if [ -s ./napaka/napaka.txt ]; then
            echo "Napaka pri preverjanju testnih skript!"
            cat ./napaka/napaka.txt
          fi

      # Klonira repozitorij
      - uses: actions/checkout@v3

      # Prevede program
      - run: make

      # Izvede teste z matriko
      - run: ./run_tests.sh ${{ matrix.test_case }}
